-- ====================================================================
-- MOHANOE INC. LEGAL PRACTICE MANAGEMENT - DATABASE SCHEMA
-- ====================================================================

-- --------------------------------------------------------------------
-- TABLE: users
-- Stores user accounts for staff and clients.
-- --------------------------------------------------------------------
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT auth.uid(),
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'client',
  password_hash TEXT NOT NULL DEFAULT '',
  password_salt TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: clients
-- Stores detailed information about clients.
-- --------------------------------------------------------------------
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES users(id) ON DELETE SET NULL, -- Link to the user account if they have one
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone_number TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: submissions
-- Stores encrypted intake payloads and redacted summaries.
-- --------------------------------------------------------------------
CREATE TABLE submissions (
  id uuid PRIMARY KEY,
  client_label TEXT NOT NULL,
  practice_area TEXT NOT NULL,
  jurisdiction TEXT NOT NULL DEFAULT 'South Africa',
  urgency_hint TEXT NOT NULL DEFAULT 'unspecified',
  status TEXT NOT NULL DEFAULT 'received',
  summary_redacted TEXT NOT NULL,
  raw_payload_encrypted TEXT NOT NULL,
  consent_to_ai BOOLEAN NOT NULL DEFAULT FALSE,
  consent_to_storage BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: assessments
-- Stores AI triage output for each intake submission.
-- --------------------------------------------------------------------
CREATE TABLE assessments (
  id uuid PRIMARY KEY,
  intake_submission_id uuid NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  model_name TEXT NOT NULL,
  matter_type TEXT NOT NULL,
  urgency TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_facts JSONB NOT NULL DEFAULT '[]'::jsonb,
  attorney_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  recommended_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
  compliance_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
  next_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence NUMERIC(4,2) NOT NULL DEFAULT 0.00,
  popia_notes JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_redacted_brief JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (intake_submission_id)
);

-- --------------------------------------------------------------------
-- TABLE: cases
-- Stores live case records created from assessed intakes.
-- --------------------------------------------------------------------
CREATE TABLE cases (
  id uuid PRIMARY KEY,
  intake_submission_id uuid NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  case_number TEXT UNIQUE NOT NULL,
  client_label TEXT NOT NULL,
  practice_area TEXT NOT NULL,
  urgency TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'triage',
  next_action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (intake_submission_id)
);

-- --------------------------------------------------------------------
-- TABLE: case_tasks
-- Stores attorney work items for each matter.
-- --------------------------------------------------------------------
CREATE TABLE case_tasks (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  due_date DATE,
  assignee_name TEXT,
  created_by TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: case_timeline
-- Tracks notes and status changes for each matter.
-- --------------------------------------------------------------------
CREATE TABLE case_timeline (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'note',
  message TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- RLS (Row-Level Security) Policies
-- Ensure that users can only access their own data.
-- --------------------------------------------------------------------

-- Enable RLS on all relevant tables
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_timeline ENABLE ROW LEVEL SECURITY;

-- Policy: Allow users to see their own client profile
CREATE POLICY "Users can view their own client data" 
ON clients FOR SELECT
USING (auth.uid() = user_id);

-- Policy: Allow staff (e.g., 'attorney', 'admin') to access all clients
CREATE POLICY "Staff can access all client data" 
ON clients FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

-- Policy: Allow staff to access all submissions
CREATE POLICY "Staff can access all submissions"
ON submissions FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

-- Policy: Allow staff to access all assessments
CREATE POLICY "Staff can access all assessments"
ON assessments FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

-- Policy: Allow staff to access all cases
CREATE POLICY "Staff can access all cases" 
ON cases FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

CREATE POLICY "Staff can access all case tasks"
ON case_tasks FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

CREATE POLICY "Staff can access all case timeline"
ON case_timeline FOR ALL
USING ( (SELECT role FROM users WHERE id = auth.uid()) IN ('admin', 'attorney', 'paralegal') );

