-- ====================================================================
-- Migration 002: Full schema bootstrap (idempotent)
-- Creates all app tables, enables RLS with zero policies (service role
-- bypasses RLS). Safe to run after 001 or on a partially set up DB.
-- Run in Supabase SQL Editor → New query → Run once.
-- ====================================================================

-- gen_random_uuid() is available via pgcrypto on Supabase.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- --------------------------------------------------------------------
-- ID type conventions (must match backend/services/*.js):
--   users.id, submissions.id, assessments.id, cases.id  → uuid
--   clients.id                                            → bigint (identity)
--   all case_id / intake_submission_id FK columns         → uuid
-- CREATE TABLE IF NOT EXISTS leaves wrong legacy PK types in place;
-- helpers below drop only EMPTY tables with incompatible types.
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._mohanoe_column_type(p_table text, p_column text)
RETURNS text
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT c.data_type
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
    AND c.table_name = p_table
    AND c.column_name = p_column
$$;

CREATE OR REPLACE FUNCTION public._mohanoe_drop_empty_wrong_pk(
  p_table text,
  p_expected_type text DEFAULT 'uuid'
)
RETURNS void
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  actual_type text;
  row_count bigint;
BEGIN
  IF to_regclass('public.' || p_table) IS NULL THEN
    RETURN;
  END IF;

  actual_type := public._mohanoe_column_type(p_table, 'id');
  IF actual_type IS NULL OR actual_type = p_expected_type THEN
    RETURN;
  END IF;

  EXECUTE format('SELECT COUNT(*) FROM public.%I', p_table) INTO row_count;
  IF row_count > 0 THEN
    RAISE EXCEPTION
      'public.% has id type % (% rows). App requires %. Backup or truncate before re-running.',
      p_table, actual_type, row_count, p_expected_type;
  END IF;

  EXECUTE format('DROP TABLE public.%I CASCADE', p_table);
  RAISE NOTICE 'Dropped empty public.% (id was %, expected %)', p_table, actual_type, p_expected_type;
END;
$$;

CREATE OR REPLACE FUNCTION public._mohanoe_drop_case_dependents()
RETURNS void
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  DROP TABLE IF EXISTS public.calendar_events CASCADE;
  DROP TABLE IF EXISTS public.billing_ledger CASCADE;
  DROP TABLE IF EXISTS public.billing_invoices CASCADE;
  DROP TABLE IF EXISTS public.documents CASCADE;
  DROP TABLE IF EXISTS public.case_timeline CASCADE;
  DROP TABLE IF EXISTS public.case_tasks CASCADE;
END;
$$;

-- --------------------------------------------------------------------
-- TABLE: users
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'client',
  password_hash TEXT NOT NULL DEFAULT '',
  password_salt TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: clients
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone_number TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Drop legacy tables with wrong PK/FK types before creating intake/case chain.
DO $$
DECLARE
  submissions_id_type text;
  cases_id_type text;
BEGIN
  submissions_id_type := public._mohanoe_column_type('submissions', 'id');
  cases_id_type := public._mohanoe_column_type('cases', 'id');

  IF submissions_id_type IS NOT NULL AND submissions_id_type <> 'uuid' THEN
    PERFORM public._mohanoe_drop_case_dependents();
    PERFORM public._mohanoe_drop_empty_wrong_pk('cases');
    PERFORM public._mohanoe_drop_empty_wrong_pk('assessments');
    PERFORM public._mohanoe_drop_empty_wrong_pk('submissions');
  END IF;

  IF cases_id_type IS NOT NULL AND cases_id_type <> 'uuid' THEN
    PERFORM public._mohanoe_drop_case_dependents();
    PERFORM public._mohanoe_drop_empty_wrong_pk('cases');
  END IF;

  IF public._mohanoe_column_type('assessments', 'intake_submission_id') IS NOT NULL
     AND public._mohanoe_column_type('assessments', 'intake_submission_id') <> 'uuid' THEN
    PERFORM public._mohanoe_drop_empty_wrong_pk('assessments');
  END IF;

  IF public._mohanoe_column_type('cases', 'intake_submission_id') IS NOT NULL
     AND public._mohanoe_column_type('cases', 'intake_submission_id') <> 'uuid' THEN
    PERFORM public._mohanoe_drop_case_dependents();
    PERFORM public._mohanoe_drop_empty_wrong_pk('cases');
  END IF;
END $$;

-- --------------------------------------------------------------------
-- TABLE: submissions
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.submissions (
  id uuid PRIMARY KEY,
  client_label TEXT NOT NULL,
  practice_area TEXT NOT NULL,
  jurisdiction TEXT NOT NULL DEFAULT 'South Africa',
  urgency_hint TEXT NOT NULL DEFAULT 'unspecified',
  status TEXT NOT NULL DEFAULT 'received',
  summary_redacted TEXT NOT NULL,
  raw_payload_encrypted TEXT NOT NULL,
  consent_to_ai BOOLEAN NOT NULL DEFAULT FALSE,
  consent_to_storage BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: assessments
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.assessments (
  id uuid PRIMARY KEY,
  intake_submission_id uuid NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  model_name TEXT NOT NULL,
  matter_type TEXT NOT NULL,
  urgency TEXT NOT NULL,
  summary TEXT NOT NULL,
  key_facts JSONB NOT NULL DEFAULT '[]'::jsonb,
  attorney_questions JSONB NOT NULL DEFAULT '[]'::jsonb,
  recommended_documents JSONB NOT NULL DEFAULT '[]'::jsonb,
  compliance_flags JSONB NOT NULL DEFAULT '[]'::jsonb,
  next_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
  confidence NUMERIC(4,2) NOT NULL DEFAULT 0.00,
  popia_notes JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_redacted_brief JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (intake_submission_id)
);

-- --------------------------------------------------------------------
-- TABLE: cases
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cases (
  id uuid PRIMARY KEY,
  intake_submission_id uuid NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
  case_number TEXT UNIQUE NOT NULL,
  client_label TEXT NOT NULL,
  practice_area TEXT NOT NULL,
  urgency TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'triage',
  next_action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (intake_submission_id)
);

-- --------------------------------------------------------------------
-- TABLE: case_tasks
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.case_tasks (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  due_date DATE,
  assignee_name TEXT,
  created_by TEXT,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: case_timeline
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.case_timeline (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL DEFAULT 'note',
  message TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: documents
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.documents (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  case_number TEXT NOT NULL,
  client_label TEXT NOT NULL,
  title TEXT NOT NULL,
  document_type TEXT NOT NULL DEFAULT 'correspondence',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft',
  encrypted_content TEXT NOT NULL,
  content_preview TEXT NOT NULL DEFAULT '',
  created_by TEXT,
  signed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: billing_invoices
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.billing_invoices (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  case_number TEXT NOT NULL,
  client_label TEXT NOT NULL,
  invoice_number TEXT UNIQUE NOT NULL,
  subject TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'ZAR',
  status TEXT NOT NULL DEFAULT 'issued',
  line_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
  vat NUMERIC(14,2) NOT NULL DEFAULT 0,
  total NUMERIC(14,2) NOT NULL DEFAULT 0,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  due_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: billing_ledger
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.billing_ledger (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  case_number TEXT NOT NULL,
  entry_type TEXT NOT NULL,
  account TEXT NOT NULL,
  amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  reference TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: calendar_events
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calendar_events (
  id uuid PRIMARY KEY,
  case_id uuid NOT NULL REFERENCES public.cases(id) ON DELETE CASCADE,
  case_number TEXT NOT NULL,
  title TEXT NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'deadline',
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  location TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: audit_events
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.audit_events (
  id uuid PRIMARY KEY,
  actor_id uuid,
  actor_name TEXT,
  actor_role TEXT,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  action TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  previous_hash TEXT NOT NULL DEFAULT 'genesis',
  entry_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: notifications
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'general',
  priority TEXT NOT NULL DEFAULT 'medium',
  recipient_role TEXT NOT NULL DEFAULT 'attorney',
  recipient_user_id uuid,
  related_entity_type TEXT,
  related_entity_id TEXT,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: report_snapshots
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.report_snapshots (
  id uuid PRIMARY KEY,
  report_type TEXT NOT NULL DEFAULT 'dashboard',
  title TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- TABLE: compliance_requests
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.compliance_requests (
  id uuid PRIMARY KEY,
  request_type TEXT NOT NULL DEFAULT 'access',
  subject_name TEXT NOT NULL,
  subject_email TEXT NOT NULL,
  case_ref TEXT,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  response_summary TEXT NOT NULL DEFAULT '',
  response_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  due_at TIMESTAMPTZ,
  fulfilled_at TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --------------------------------------------------------------------
-- Align users columns if the table existed before this migration
-- --------------------------------------------------------------------
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'client';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS password_salt TEXT NOT NULL DEFAULT '';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.users SET is_active = TRUE WHERE is_active IS NULL;

-- --------------------------------------------------------------------
-- RLS: enable on all tables, zero policies (backend uses service role)
-- --------------------------------------------------------------------
DO $$
DECLARE
  tbl text;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'users',
    'clients',
    'submissions',
    'assessments',
    'cases',
    'case_tasks',
    'case_timeline',
    'documents',
    'billing_invoices',
    'billing_ledger',
    'calendar_events',
    'audit_events',
    'notifications',
    'report_snapshots',
    'compliance_requests'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
  END LOOP;
END $$;

-- Reload PostgREST schema cache so API sees new tables immediately.
NOTIFY pgrst, 'reload schema';
